# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python



# Trigger the Workflow on any push to the main Branch or Pull Request

name: Python Application C.I.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# permissions:
#   contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:


    # 1. CheckOut the Code From Repository
        - name: Check out Code
          uses: actions/checkout@v4

          
    # 2. SetUp the Python Environment

        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"

    # 3. Install dependencies
    
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    
    #4. Run Tests
        - name: Test with pytest
          run: |
            pytest
